### ISSUE TITLE
Mangling arguments

### ISSUE THREAD

**Issue by neerolyte** [pendashteh/safe#1]
Currently arguments are incorrectly encoded, e.g:

```
$ ./safe rm thing\ with\ spaces
Are you sure you want to 'rm thing with spaces'? [y/n]
y
rm: cannot remove 'thing': No such file or directory
rm: cannot remove 'with': No such file or directory
rm: cannot remove 'spaces': No such file or directory
```

Setting args like `args=${*}` means you're taking the entire set of args and creating it as a single string, meaning you need to use it unquoted [here](https://github.com/pendashteh/safe/blob/bc922e0/safe).

This makes safe less safe than normal usage because you might accidentally remove the wrong thing (e.g if "thing" existed on its own, it would have been removed above).

You should just execute `"$@"` - bash double quoting correctly expands all elements of that array to pass in to whatever it needs to.

**Comment by pendashteh** [comment]
Thanks @neerolyte for bringing this up. This is a bug. "$@" does not fix it tho.

Here is a good read:
https://yakking.branchable.com/posts/whitespace-safety/

I managed to fix this, but I would like to replace whitespaces with backslash in the display message, as the next step.

**Comment by pendashteh** [comment]
I wish I had bash script unit testing sorted. This would have made a good test.
